### ISSUE TITLE
Error: not found: object ReleaseTransformations

### ISSUE THREAD

**Issue by chank** [qifun/sbt-haxe#63] opened 2015-08-20 01:43 UTC
I use the project [sbt-haxe-sample](https://github.com/new-cbs/sbt-haxe-sample) to test the sbt-haxe, and it failed with the following message:

```
F:\workspace\sbt-haxe-sample>sbt
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
[info] Loading global plugins from C:\Users\Administrator\.sbt\0.13\staging\b479b818d45e59945587\sbteclipse\project
[info] Loading global plugins from C:\Users\Administrator\.sbt\0.13\plugins
F:\workspace\sbt-haxe-sample\project\sbt-haxe\build.sbt:23: error: not found: object ReleaseTransformations
import ReleaseTransformations._
       ^
[error] Type error in expression
```

**Comment by chank** [comment] 2015-08-20 01:45
@Atry It should be fixed before publish the new version.

**Comment by chank** [comment] 2015-08-20 10:20
Still exist

**Comment by Atry** [comment] 2015-08-20 12:51
It's not a bug in sbt-haxe per se. sbt-haxe-sample
<https://github.com/new-cbs/sbt-haxe-sample> should add these plugins as
well.

chank <notifications@github.com>于2015年8月20日周四 下午6:20写道：

> Still exist
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qifun/sbt-haxe/issues/63#issuecomment-132966050>.
>
-- 
杨博 (Yang Bo)

**Comment by Atry** [comment] 2015-09-16 01:30
@chank Could you close this issue because it's not a bug in this repository.

**Closed** 2015-09-16 01:47 UTC
